# Generated by Django 5.2.7 on 2026-02-10 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('expiry_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='donations/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Collected', 'Collected')], default='Available', max_length=10)),
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_id', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
