# Generated by Django 5.2.7 on 2026-02-10 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='id',
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='donation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
